Typescript implementation
esthereis/ns-itinerary pull request #4
Opened 2024-12-12 09:36 UTC by esthereis

2025-01-09 11:39 UTC, artursoareshsv requested changes

2025-01-09 11:39 UTC, artursoareshsv commented on .env
You shouldn't version `.env` files. Usually, .env files contain sensitive information like API keys and should not be shared.

2025-01-09 11:39 UTC, artursoareshsv commented on .gitignore
Not a good practice removing `.env` from ignore.

2025-01-09 11:39 UTC, artursoareshsv commented on index.html
> +    <title>Vite + React + TS</title>
```suggestion
    <title>NS Itinerary</title>
```

2025-01-09 11:39 UTC, artursoareshsv commented on package.json
> +  "name": "ns-replacement",
```suggestion
  "name": "ns-itinerary",
```

2025-01-09 11:39 UTC, artursoareshsv commented on src/components/Input.tsx
> +export default function Input({ placeholder, onSelect }: Props) {
```suggestion
export default function StationAutocomplete({ placeholder, onSelect }: Props) {
```
If you want to have a specific input such as this one, I suggest you make the name of the component specific too. Unless, you want to make it reusable.
Btw, this component is autocomplete, it has more features than a simple input.

2025-01-09 11:39 UTC, artursoareshsv commented on src/components/TripCard.tsx
>      // const duration = pathDuration < 30 ? pathDuration : pathDuration / 60;
```suggestion
```
Can you remove commented code?

2025-01-09 11:39 UTC, artursoareshsv commented on src/components/TripList.tsx
> +// key={trip.checksum}
```suggestion
```
It is a good practice to keep your code clean, without commented code.

2025-01-09 11:39 UTC, artursoareshsv commented on src/services/travel.ts
> +        },
I suggest you to take a look on how to use [Axios instance](https://axios-http.com/docs/instance) to centralize configurations such as your headers.

2025-01-13 10:17 UTC, esthereis commented
Exercise corrected.

2025-01-14 08:41 UTC, artursoareshsv approved these changes

2025-01-14 08:45 UTC, merged